-- DEL DE BODEGA
insert into compra(usuario,sucursal,fecha,total_compra) values (1,1,CURRENT_DATE,0);//generar compra

select c.codigo, s.nombre AS sucursal, c.fecha, c.total_compra from bodegas.compra
c join sucursales.sucursal s on(c.sucursal=s.identificacion); --seleccionar todas las compras


-- insertando los productos
-- Consolas
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola PlayStation 5', 4999.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola Xbox Series X', 4999.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola Nintendo Switch OLED', 3999.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola PlayStation 5 Digital Edition', 3999.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola Xbox Series S', 2999.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola Nintendo Switch Lite', 2499.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola PlayStation 4 Pro', 3499.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola Xbox One X', 3299.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola PlayStation VR', 2899.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola Nintendo Wii U', 1999.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola PlayStation 3', 1799.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola Xbox 360', 1699.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola Nintendo 3DS XL', 1499.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola PlayStation Portable', 1299.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola Xbox One', 2999.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola Nintendo GameCube', 1199.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola PlayStation 2', 899.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola Xbox', 799.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola Nintendo Wii', 799.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola Sega Dreamcast', 499.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola Atari Jaguar', 399.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola PlayStation Classic', 199.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola Game Boy Advance', 149.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola PlayStation Vita', 199.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola Nintendo DS', 179.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola Nintendo 64', 249.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola Sega Saturn', 179.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola Neo Geo Pocket', 99.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola PlayStation 1', 99.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola Game Boy Color', 89.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola Game Boy', 69.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola Sega Genesis', 79.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola Super Nintendo', 99.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola TurboGrafx-16', 119.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola Neo Geo', 299.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola Intellivision', 99.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola ColecoVision', 129.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola Magnavox Odyssey', 149.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola Odyssey 2', 119.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola Atari 2600', 149.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola Atari 7800', 139.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola TurboGrafx-CD', 179.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola Neo Geo CD', 199.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola PlayStation 2 Slim', 249.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola Xbox 360 Elite', 249.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola Nintendo Wii Mini', 129.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola Sega Genesis Mini', 79.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola Super Nintendo Classic', 99.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola PlayStation Classic Mini', 129.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola Neo Geo Mini', 99.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola Atari Flashback 8', 89.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola ColecoVision Flashback', 69.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola Game Boy Micro', 89.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola Game Boy Advance SP', 149.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola Sega Dreamcast Mini', 149.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola Atari Jaguar CD', 179.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola Sega Saturn Console', 179.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola Commodore 64 Mini', 119.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola Intellivision Flashback', 89.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola Commodore 128', 129.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola TurboGrafx-16 Mini', 139.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola Atari Lynx', 139.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola Game Boy Advance Original', 129.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola Sega Genesis Model 2', 159.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola PlayStation 5 Pro', 5499.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola Xbox Series X Elite', 5499.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola Nintendo Switch Pro', 4999.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola PlayStation 5 Slim', 4499.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola Xbox Series S Digital', 3499.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola Nintendo Switch OLED Lite', 3999.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola PlayStation 4 Slim', 2999.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola Xbox One S', 2499.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola Nintendo 3DS XL Limited Edition', 1799.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola PlayStation Portable Slim', 1399.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola Xbox One X Elite', 3299.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola Nintendo Wii U Deluxe', 2199.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola PlayStation 3 Super Slim', 1999.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola Xbox 360 Slim', 1799.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola Nintendo 3DS', 1499.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola PlayStation Vita Slim', 1499.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola Nintendo 64 Limited Edition', 299.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola Sega Saturn Limited Edition', 229.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola Neo Geo Pocket Limited', 139.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola PlayStation 1 Classic', 119.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola Game Boy Color Limited', 109.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola Game Boy Advance SP Special Edition', 169.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola Sega Dreamcast Special', 219.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola Atari Jaguar Limited', 179.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola Commodore 64 Full Set', 179.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola Game Gear Limited Edition', 149.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola Neo Geo Pocket Color Special', 159.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola Sega Master System Limited', 179.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola Intellivision Complete Set', 129.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola Commodore 128 Complete', 149.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola TurboGrafx-16 Complete', 169.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola Atari Lynx Special Edition', 159.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola Game Boy Advance Original Special', 139.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola Sega Genesis Model 2 Special', 159.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola PlayStation 5 Pro Max', 5999.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola Xbox Series X Ultra', 5999.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola Nintendo Switch Ultra', 5499.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola PlayStation 5 Mega', 5499.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola Xbox Series S Plus', 4499.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola Nintendo Switch Elite', 4999.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola PlayStation 4 Pro Plus', 3999.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola Xbox One Elite', 3499.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola Nintendo Wii U Pro', 2599.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola PlayStation 3 Pro', 2199.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola Xbox 360 Pro', 1899.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola Nintendo 3DS XL Deluxe', 1599.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Consola PlayStation Portable Deluxe', 1399.99, true);

-- Videojuegos
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Videojuego The Legend of Zelda: Tears of the Kingdom', 69.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Videojuego God of War Ragnarök', 69.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Videojuego Elden Ring', 59.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Videojuego Horizon Forbidden West', 69.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Videojuego Final Fantasy XVI', 69.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Videojuego Resident Evil 4 Remake', 59.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Videojuego Call of Duty: Modern Warfare II', 69.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Videojuego Starfield', 69.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Videojuego Spider-Man 2', 69.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Videojuego Metroid Prime Remastered', 59.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Videojuego Gran Turismo 7', 69.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Videojuego Dead Space Remake', 59.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Videojuego Assassin’s Creed Mirage', 69.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Videojuego Diablo IV', 69.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Videojuego Hogwarts Legacy', 69.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Videojuego Final Fantasy VII Remake Intergrade', 69.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Videojuego Monster Hunter Rise', 59.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Videojuego Pokémon Scarlet', 59.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Videojuego Pokémon Violet', 59.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Videojuego Forza Horizon 5', 69.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Videojuego Granblue Fantasy Versus', 59.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Videojuego Tekken 8', 69.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Videojuego Street Fighter 6', 59.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Videojuego Baldur’s Gate 3', 69.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Videojuego Yakuza: Like a Dragon', 59.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Videojuego Red Dead Redemption II', 59.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Videojuego The Last of Us Part I', 69.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Videojuego Ghost of Tsushima', 59.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Videojuego Deathloop', 59.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Videojuego Returnal', 59.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Videojuego Ratchet & Clank: Rift Apart', 69.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Videojuego Control Ultimate Edition', 59.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Videojuego Hades', 39.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Videojuego Disco Elysium', 49.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Videojuego Celeste', 19.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Videojuego Ori and the Will of the Wisps', 29.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Videojuego Cuphead', 29.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Videojuego Hollow Knight', 29.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Videojuego Slay the Spire', 24.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Videojuego Dead Cells', 29.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Videojuego Stardew Valley', 14.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Videojuego Among Us', 4.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Videojuego A Short Hike', 7.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Videojuego Katana ZERO', 14.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Videojuego Hyper Light Drifter', 19.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Videojuego Bastion', 14.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Videojuego Transistor', 19.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Videojuego Pyre', 19.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Videojuego Crypt of the NecroDancer', 14.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Videojuego The Banner Saga', 29.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Videojuego FTL: Faster Than Light', 9.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Videojuego The Witness', 39.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Videojuego Outer Wilds', 29.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Videojuego Papers, Please', 9.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Videojuego Limbo', 9.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Videojuego Inside', 14.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Videojuego Little Nightmares', 29.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Videojuego What the Box?', 9.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Videojuego Spelunky 2', 19.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Videojuego Moon Hunters', 19.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Videojuego A Hat in Time', 29.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Videojuego Yoku’s Island Express', 19.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Videojuego Deadly Premonition', 29.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Videojuego To The Moon', 9.99, true);

-- Accesorios
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Accesorio Controlador Xbox Elite Series 2', 149.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Accesorio Controlador DualSense Wireless', 69.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Accesorio Controlador Nintendo Switch Pro', 79.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Accesorio Estación de Carga para PS5', 129.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Accesorio Estación de Carga para Xbox Series X', 129.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Accesorio Estación de Carga para Nintendo Switch', 119.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Accesorio Auriculares Gaming HyperX', 89.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Accesorio Auriculares Gaming SteelSeries', 109.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Accesorio Cargador Dual para PS4', 79.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Accesorio Cargador Dual para Xbox One', 79.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Accesorio Adaptador USB para PS5', 49.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Accesorio Adaptador HDMI 4K', 29.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Accesorio Cable de Carga Rápida para Switch', 24.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Accesorio Cable de Carga para PS4', 19.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Accesorio Cable de Carga para Xbox One', 19.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Accesorio Soporte para PS5', 39.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Accesorio Soporte para Xbox Series X', 39.99, true);
INSERT INTO productos.productos (nombre, precio_unitario_venta, en_venta) VALUES ('Accesorio Soporte para Nintendo Switch', 34.99, true);


-- insertandolos en los sucursales
-- Insertar con id_producto del 1 al 50
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (1, 1, 15, 20, 5, 12);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (2, 1, 18, 22, 6, 7);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (3, 1, 12, 30, 7, 8);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (4, 1, 10, 25, 8, 9);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (5, 1, 14, 23, 4, 11);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (6, 1, 20, 17, 5, 10);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (7, 1, 16, 28, 2, 12);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (8, 1, 13, 22, 9, 7);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (9, 1, 11, 26, 6, 8);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (10, 1, 19, 30, 3, 9);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (11, 1, 25, 20, 8, 12);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (12, 1, 14, 24, 7, 5);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (13, 1, 17, 27, 4, 11);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (14, 1, 22, 15, 5, 8);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (15, 1, 12, 23, 6, 10);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (16, 1, 18, 30, 3, 12);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (17, 1, 21, 25, 9, 6);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (18, 1, 13, 28, 2, 7);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (19, 1, 16, 22, 4, 8);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (20, 1, 11, 18, 5, 12);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (21, 1, 20, 19, 6, 7);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (22, 1, 15, 26, 8, 9);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (23, 1, 14, 30, 3, 10);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (24, 1, 18, 24, 9, 5);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (25, 1, 19, 21, 7, 11);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (26, 1, 12, 20, 6, 9);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (27, 1, 20, 18, 5, 7);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (28, 1, 17, 26, 2, 10);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (29, 1, 15, 23, 8, 12);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (30, 1, 13, 30, 4, 6);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (31, 1, 22, 17, 3, 8);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (32, 1, 19, 26, 5, 11);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (33, 1, 12, 21, 7, 9);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (34, 1, 16, 29, 2, 12);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (35, 1, 18, 20, 6, 5);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (36, 1, 25, 28, 4, 7);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (37, 1, 10, 22, 9, 6);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (38, 1, 20, 18, 2, 11);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (39, 1, 17, 30, 5, 8);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (40, 1, 21, 20, 6, 12);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (41, 1, 12, 24, 8, 7);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (42, 1, 18, 29, 3, 10);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (43, 1, 15, 25, 7, 12);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (44, 1, 13, 22, 6, 8);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (45, 1, 20, 18, 9, 10);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (46, 1, 17, 28, 5, 7);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (47, 1, 25, 30, 2, 9);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (48, 1, 14, 21, 8, 11);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (49, 1, 12, 25, 7, 10);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (50, 1, 18, 19, 3, 12);

-- Insertar con id_producto del 100 al 150
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (100, 1, 14, 20, 5, 11);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (101, 1, 22, 25, 6, 8);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (102, 1, 16, 30, 2, 10);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (103, 1, 19, 28, 7, 9);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (104, 1, 12, 26, 4, 6);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (105, 1, 18, 20, 8, 12);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (106, 1, 21, 30, 3, 11);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (107, 1, 14, 22, 9, 7);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (108, 1, 16, 24, 6, 10);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (109, 1, 20, 18, 5, 12);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (110, 1, 22, 27, 7, 9);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (111, 1, 12, 30, 2, 8);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (112, 1, 18, 20, 4, 10);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (113, 1, 25, 22, 6, 11);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (114, 1, 19, 25, 3, 9);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (115, 1, 14, 18, 8, 7);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (116, 1, 20, 30, 5, 10);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (117, 1, 22, 25, 6, 12);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (118, 1, 16, 28, 2, 9);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (119, 1, 18, 22, 7, 11);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (120, 1, 21, 27, 4, 8);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (121, 1, 13, 30, 3, 12);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (122, 1, 25, 20, 6, 10);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (123, 1, 12, 24, 8, 7);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (124, 1, 18, 22, 5, 9);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (125, 1, 20, 30, 2, 11);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (126, 1, 22, 25, 6, 8);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (127, 1, 14, 18, 7, 10);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (128, 1, 16, 30, 3, 9);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (129, 1, 20, 22, 6, 12);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (130, 1, 18, 24, 4, 11);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (131, 1, 21, 27, 2, 10);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (132, 1, 25, 20, 5, 8);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (133, 1, 12, 30, 3, 9);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (134, 1, 18, 26, 7, 10);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (135, 1, 20, 20, 8, 12);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (136, 1, 22, 24, 4, 11);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (137, 1, 16, 30, 2, 9);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (138, 1, 20, 25, 6, 12);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (139, 1, 18, 22, 5, 8);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (140, 1, 21, 27, 7, 10);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (141, 1, 25, 20, 4, 11);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (142, 1, 12, 30, 3, 8);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (143, 1, 18, 26, 2, 12);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (144, 1, 20, 28, 5, 10);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (145, 1, 22, 20, 6, 12);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (146, 1, 16, 25, 4, 7);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (147, 1, 20, 22, 3, 11);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (148, 1, 18, 26, 7, 10);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (149, 1, 21, 30, 5, 8);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (150, 1, 25, 20, 6, 11);


-- Insertar con id_producto del 1 al 50
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (1, 2, 18, 25, 6, 11);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (2, 2, 12, 22, 3, 8);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (3, 2, 20, 28, 7, 10);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (4, 2, 25, 20, 8, 12);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (5, 2, 14, 18, 5, 9);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (6, 2, 22, 26, 4, 10);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (7, 2, 18, 30, 2, 12);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (8, 2, 21, 24, 6, 7);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (9, 2, 19, 27, 3, 11);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (10, 2, 15, 30, 7, 8);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (11, 2, 24, 22, 5, 12);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (12, 2, 17, 20, 8, 9);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (13, 2, 12, 28, 4, 10);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (14, 2, 22, 25, 3, 11);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (15, 2, 18, 30, 6, 8);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (16, 2, 21, 20, 7, 12);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (17, 2, 25, 22, 4, 11);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (18, 2, 14, 18, 8, 10);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (19, 2, 19, 27, 5, 9);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (20, 2, 17, 24, 6, 12);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (21, 2, 25, 30, 2, 10);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (22, 2, 12, 26, 4, 11);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (23, 2, 22, 24, 3, 8);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (24, 2, 18, 30, 7, 9);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (25, 2, 21, 22, 5, 10);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (26, 2, 19, 30, 8, 12);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (27, 2, 14, 25, 6, 11);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (28, 2, 12, 28, 4, 9);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (29, 2, 18, 24, 5, 10);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (30, 2, 22, 20, 7, 12);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (31, 2, 25, 26, 3, 11);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (32, 2, 21, 24, 6, 8);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (33, 2, 17, 30, 5, 9);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (34, 2, 19, 22, 8, 10);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (35, 2, 25, 30, 4, 11);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (36, 2, 12, 26, 7, 12);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (37, 2, 22, 20, 5, 10);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (38, 2, 18, 28, 3, 9);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (39, 2, 21, 24, 6, 12);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (40, 2, 25, 22, 4, 10);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (41, 2, 14, 18, 7, 11);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (42, 2, 12, 30, 8, 9);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (43, 2, 18, 24, 5, 12);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (44, 2, 22, 26, 3, 10);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (45, 2, 25, 20, 7, 11);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (46, 2, 17, 30, 4, 9);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (47, 2, 19, 22, 6, 8);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (48, 2, 14, 28, 5, 11);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (49, 2, 22, 24, 7, 9);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (50, 2, 18, 26, 4, 10);

-- Insertar con id_producto del 100 al 125
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (100, 2, 15, 20, 5, 12);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (101, 2, 22, 30, 6, 9);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (102, 2, 20, 25, 7, 10);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (103, 2, 18, 30, 3, 11);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (104, 2, 21, 22, 4, 8);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (105, 2, 17, 28, 8, 12);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (106, 2, 14, 24, 5, 9);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (107, 2, 25, 30, 6, 11);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (108, 2, 22, 20, 7, 10);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (109, 2, 18, 26, 3, 12);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (110, 2, 20, 25, 6, 8);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (111, 2, 17, 30, 4, 9);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (112, 2, 22, 24, 5, 10);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (113, 2, 18, 28, 6, 12);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (114, 2, 25, 20, 7, 11);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (115, 2, 20, 26, 4, 10);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (116, 2, 21, 30, 5, 9);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (117, 2, 14, 24, 6, 12);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (118, 2, 22, 20, 7, 8);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (119, 2, 18, 28, 5, 11);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (120, 2, 25, 22, 4, 10);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (121, 2, 17, 30, 6, 9);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (122, 2, 20, 24, 5, 12);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (123, 2, 22, 26, 4, 11);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (124, 2, 18, 20, 7, 10);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (125, 2, 25, 30, 5, 12);


-- Insertar con id_producto del 1 al 50
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (1, 3, 16, 22, 4, 9);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (2, 3, 24, 27, 5, 10);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (3, 3, 19, 30, 7, 12);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (4, 3, 21, 25, 6, 8);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (5, 3, 18, 20, 3, 11);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (6, 3, 23, 28, 4, 9);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (7, 3, 15, 24, 5, 10);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (8, 3, 20, 30, 6, 12);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (9, 3, 22, 23, 3, 8);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (10, 3, 17, 29, 7, 11);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (11, 3, 18, 25, 4, 10);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (12, 3, 23, 20, 5, 9);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (13, 3, 19, 26, 6, 12);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (14, 3, 20, 30, 3, 11);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (15, 3, 25, 28, 4, 9);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (16, 3, 21, 20, 7, 12);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (17, 3, 15, 26, 5, 10);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (18, 3, 22, 24, 6, 9);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (19, 3, 18, 30, 4, 11);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (20, 3, 23, 22, 5, 8);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (21, 3, 20, 29, 6, 10);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (22, 3, 18, 25, 3, 11);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (23, 3, 21, 30, 4, 12);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (24, 3, 19, 26, 5, 9);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (25, 3, 22, 24, 6, 10);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (26, 3, 17, 20, 4, 11);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (27, 3, 20, 28, 5, 9);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (28, 3, 23, 30, 6, 12);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (29, 3, 18, 25, 3, 10);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (30, 3, 21, 30, 7, 9);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (31, 3, 17, 22, 4, 11);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (32, 3, 20, 28, 5, 12);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (33, 3, 22, 26, 6, 8);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (34, 3, 25, 24, 7, 11);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (35, 3, 18, 20, 4, 9);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (36, 3, 21, 30, 5, 10);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (37, 3, 15, 22, 6, 12);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (38, 3, 24, 25, 7, 8);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (39, 3, 22, 30, 4, 11);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (40, 3, 19, 26, 5, 12);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (41, 3, 18, 28, 6, 10);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (42, 3, 21, 20, 7, 9);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (43, 3, 25, 30, 4, 11);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (44, 3, 20, 22, 5, 10);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (45, 3, 23, 24, 6, 12);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (46, 3, 19, 30, 7, 8);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (47, 3, 25, 20, 4, 9);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (48, 3, 22, 30, 5, 11);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (49, 3, 20, 24, 6, 12);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (50, 3, 18, 22, 7, 10);

-- Insertar con id_producto del 100 al 125
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (100, 3, 15, 24, 4, 12);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (101, 3, 23, 30, 5, 11);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (102, 3, 19, 25, 6, 10);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (103, 3, 22, 28, 3, 9);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (104, 3, 18, 20, 4, 11);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (105, 3, 21, 26, 7, 12);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (106, 3, 17, 28, 6, 10);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (107, 3, 25, 30, 5, 12);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (108, 3, 18, 24, 4, 9);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (109, 3, 20, 22, 5, 11);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (110, 3, 19, 30, 6, 12);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (111, 3, 22, 26, 7, 10);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (112, 3, 18, 20, 4, 12);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (113, 3, 25, 30, 5, 11);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (114, 3, 20, 22, 6, 10);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (115, 3, 17, 25, 7, 12);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (116, 3, 22, 30, 4, 11);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (117, 3, 19, 26, 5, 10);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (118, 3, 21, 24, 6, 12);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (119, 3, 18, 22, 7, 9);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (120, 3, 25, 20, 4, 10);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (121, 3, 22, 28, 5, 12);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (122, 3, 20, 30, 6, 8);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (123, 3, 17, 25, 7, 10);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (124, 3, 18, 22, 4, 11);
INSERT INTO sucursales.productos_sucursal(id_producto, id_sucursal, cantidad_estanteria, cantidad_bodega, pasillo_bodega, pasillo_estanteria) VALUES (125, 3, 21, 30, 5, 12);


-- insertando 8 clientes
INSERT INTO clientes.clientes (nombre, telefono, nit) VALUES
('Carlos Pérez', 3101234567, '123456789-1'),
('María Gómez', 3159876543, '987654321-0'),
('Juan Rodríguez', 3207654321, '456789123-2'),
('Ana Martínez', 3123456789, '654321987-3'),
('Pedro Fernández', 3198765432, '789123456-4'),
('Laura Sánchez', 3112345678, '321654987-5'),
('Luis Ramírez', 3167654321, '987321654-6'),
('Sofía Morales', 3186543210, '123789654-7');


